name: Peter Cashel
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
encoding: UTF-8
author: Peter Cashel

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title
  posts_mods:
    output: true
    permalink: /mods/:year/:month/:day/:title

plugins:
  - jekyll-feed